name: Commit Change

on:
  push:
    branches:
      - main

jobs:
  create-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Text File
        run: echo "Hello, World!" > file.txt

      - name: Set up Git
        run: |
          git config --global user.name "wbrand"
          git config --global user.email "your-email@example.com"
          git config --global credential.helper store

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add file.txt
          git commit -m "Add file.txt"
          git push origin main
